### ISSUE TITLE
Session Expired Login Modal - CP and CO

### ISSUE THREAD

**Issue by cbeasley-sbb** [stellarbb/devops#34]
### Bug

The existing login modal form only logs the user into CP when the session expires.

We need to add logic that checks the session status to CO pages.

We need the modal to login the user into both CO and CP.

### Steps to reproduce the behavior and expected behavior

Open at least 3 tabs into CO and CP pages.

For testing purposes in my sandbox add a query parameter "demo=1" to the URL to cause more frequent session checking.

Logout of one of the tabs and in moments the login modal should be rendered in the other tabs.

Login from one of the tabs.

After a few moments the login modal ought to close on all other tabs.

### Example pages to use:
[Account Edit Page](https://cp-cbeasley.stellarbb.com/accounts/edit/71226?demo=1)
[CP Dashboard](https://cp-cbeasley.stellarbb.com/dashboard?demo=1)
[CO Dashboard](https://cp-cbeasley.stellarbb.com/co/index.php?demo=1)
[Account Edit Page](https://cp-cbeasley.stellarbb.com/accounts?demo=1)

**Comment by cbeasley-sbb** [comment]
@jalcantaras Could you assist with helping me get the new login modal to display properly in the various situations.

The file that is providing the content for the modal is coming from:
/var/www/centralpoint.spartan-net.com/app/webroot/co/htdocs/custom/common/loginmodal.php

There is also some Javascript that has impact on the modal content located in the "ShowForceLoginModal" function:

/var/www/common-assets/js/spnet/page-context.js

**Comment by jalcantaras** [comment]
This is fix. Cross tested on Firefox, Edge, Chrome and inspector mobile.
Worked on CSS custom tab. And file
/var/www/centralpoint.spartan-net.com/app/webroot/co/htdocs/custom/common/loginmodal.php

You need to clean cache and hard reset on each page to test.

@cbeasley-sbb

**Comment by cbeasley-sbb** [comment]
@jalcantaras  The modal looks the same for the different contexts based on my inspections depicted in the screenshots below.

### Bootstrap Color Admin Page - Account Edit
<img width="1356" alt="Screenshot_2024_10_21_at_12 19 24_PM" src="https://github.com/user-attachments/assets/83991841-5444-42d1-b195-023e797a1ff8">

### Foundation Page - Accounts Dashboard
<img width="1340" alt="Screenshot_2024_10_21_at_12 19 17_PM" src="https://github.com/user-attachments/assets/8f0b43ad-8730-4803-a984-26d35e856e88">


### CO Page Ticket Card
<img width="1333" alt="Screenshot_2024_10_21_at_12 19 01_PM" src="https://github.com/user-attachments/assets/9e68f859-5220-4e5e-b153-69c4c990787e">

**Comment by cbeasley-sbb** [comment]
The changes for this task have been staged.

We need to deploy in the following order. 
### NOTE:  If as anticipated, this is deployed with  Ticket Integration then that order works as well.

1. CO common Module
2. Common-Assets
3. CentralPoint

### Post-Deployment
All CO/CP Users must clear cache and reload all pages to get the latest JS version for the PageContext session activity monitoring.
